### PR TITLE
Edit wording in CFF introduction

### PR DESCRIPTION
**Pull request by sdruskat**
### Summary

Edits of the page describing CFF file usage.

Note: branched from https://github.com/NLeSC/the-turing-way/tree/software-citation.

### List of changes proposed in this PR (pull-request)

- _Edit the CFF page introduction wording slightly for precision and understanability_
- _Editor the rationale section of the CFF page_

### What should a reviewer concentrate their feedback on?

- [ ] Do the changes make the changed sections better?
- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by sdruskat** [comment]
I think the intro already said what it needed to say, I've made some wording and format changes. This is good to go from my side. I'll look at it again over the next 2 days to see if I can think of something to improve.

Thanks for all of your work!

**Comment by fdiblen** [comment]
> I think the intro already said what it needed to say, I've made some wording and format changes. This is good to go from my side. I'll look at it again over the next 2 days to see if I can think of something to improve.
> 
> Thanks for all of your work!

Thank you very much @sdruskat! We plan to finalize it tomorrow. It would be nice to get your feedback on the final version before this gets merged. I will keep you in the loop.

**Comment by abelsiqueira** [comment]
Thanks for the contribution!

**Comment by sdruskat** [comment]
Hi @abelsiqueira and @fdiblen, sure, thank you for putting in the bulk of the work.
Let me know when/where to look at something, I have some time left today and tomorrow morning.

Cheers!

**Comment by abelsiqueira** [comment]
Hi @sdruskat. It should be ready for another round of review, if you have the time. Here's the link: https://github.com/alan-turing-institute/the-turing-way/pull/2161
Thanks again.

**Comment by sdruskat** [comment]
> Hi @sdruskat. It should be ready for another round of review, if you have the time. Here's the link: [alan-turing-institute#2161](https://github.com/alan-turing-institute/the-turing-way/pull/2161) Thanks again.

Cheers, can do tomorrow morning.

**Pull request merged**
