### PR TITLE
Line breaks, formatting, acronyms in software license

### PR DESCRIPTION
**Pull request by malvikasharan**
Looks really good! Thank you for splitting the original file.

### Summary

Fixes #<NUM>

* Adding line break in the introduction part.
* Minor formatting in the software license

### List of changes proposed in this PR (pull-request)

* Definition of software license
* Acronyms of licenses
* line break is in the turing way style guide.

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@c-martinez and @sverhoeven Can you help me understand if the software documentation should be mentioned in the software license sub-chapter or should that be linked to another sub-chapter named as 'software documentation license'?

**Comment by sverhoeven** [comment]
Which `software documentation` are you talking about? In which Markdown files is this information now?

Also the PR is being merged into the wrong branch (master), it should be be the `choose-a-license-868` branch.

**Comment by mkuzak** [comment]
I believe this is about the license for software documentation. @malvikasharan please correct if I'm wrong.

**Comment by malvikasharan** [comment]
Exactly @mkuzak! @sverhoeven you mean my PR? I have requested to merge in this branch.

I have left a comment on your PR to the master: https://github.com/alan-turing-institute/the-turing-way/pull/880

**Comment by malvikasharan** [comment]
I see what you meant @sverhoeven. I changed the base so it merges to the right branch.

**Comment by sverhoeven** [comment]
Yep, thanks for the change of the into branch and the PR

**Comment by LourensVeen** [comment]
About software documentation, I think @malvikasharan is talking about licenses specifically for software documentation. The only one I know of is the GNU Free Documentation License. In most cases, it's probably best to put the documentation in the repo with the code, and license it under the same license as the software. If it's Markdown or ReStructuredText then you actually have a source and a compiled form, so that makes even more sense. I'm not that familiar with the GNU FDL, but as I recall it allows you to require anyone making a book out of the docs to put certain text on the front and/or back cover. There are some more restrictions in it that make it a bit more difficult to deal with IIRC.

I personally wouldn't be surprised to find something about documentation in the software section, but that usually just means that everyone else would. If it's just about the GFDL then a separate chapter is maybe too much. On the other hand, maybe it could be extended a bit towards licencing technical reports and white papers and slide decks and posters and such? That could be a separate chapter I guess, and include the Creative Commons licenses as well.

**Comment by c-martinez** [comment]
If I understand correctly, we do not have (yet) content for this section. In which sense, I would think we can add it as a sub-chapter of the Licenses chapter and --- if at some point it grows too large -- we could move to its own chapter.

**Comment by c-martinez** [comment]
Changes in this PR are ok. Merging.

We can continue the discussion about software documentation sub-chapter in  alan-turing-institute#880

**Pull request merged**
